language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: "RLyOz359HDLZlcSZQyYuCGz30+x1wXrkLX6zxTkNGsYChqSYTt1AG1R1h5w5boyZDxFcmZKxBOEmel3QeBoL5r7moeeuku+qKqjTM5hPJYzEWhMQRBd2RQm5kGKYjE/pJgOZ90g+AsHFVCmbbaDBRQA93OUapDi+ifgs42GTmiueVydEq76hxb6GiinKnV1duS0FmY3BwnSTx002NPf1O7Z/6n/PD+HRxe07rzqRCChkduEyAINvzIfVQILq/xpxPf2TBlizKVGmRGtC84PRIpETRK3FC5PF5h982YmPOLTgUuUE3NGNPEOseaIFmXTq3TbM8yfa2DEtLAS+O9lv8nUqZ9wgyucrnWRTeKM/SlKzwJKcADKjTVvhowME4KR7FxTKAAnd2iQvsYwveL/xLCZap4bqbd8K1p/Ou/Cz4rCSH8Px6/1ZGHbiskHjMU107tenCMV9lPvFlqTM2GTY2tdrCvDyYNoDOrBjInT4/ohwW/2ObPo2MiEjyjBBu9BH6zulkc1jIALc1b+2u8+qfpDifug693mqy3+FqpqPUEGlVVrGsvRHMG5c+ebdvpBfREpIMWc/4NNgGY4CEFDWy0c2vOS1wAY9pL8T3scIJahr1gfiC5OrwzHk3g8oeOWYFALCeggNeREUHaJ/fs6CtNpVxhGkmmO2k0fRBDRwiAc="
  app: viewing-party-gkw
  run: rails db:migrate
